import Nav from "./(components)/Nav";
import "./globals.css";
import { Outfit } from "next/font/google";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;
const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Issue Tracker",
  description: "Generated by Hillary Gilbert",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-page text-main-text">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
